### ISSUE TITLE
CocoaLumberjack causing build error: "Use of undeclared identifier 'ddLogLevel'"

### ISSUE THREAD

**Issue by chris59david** [qwasi/ios-library#1]
I think it's related to this problem, CocoaLumberjack causing a breaking change from 2.0 to 2.0.1
https://github.com/CocoaLumberjack/CocoaLumberjack/issues/542

Could set the podspec to require 2.0 for now till they fix it?

**Comment by rodriguise** [comment]
Fixed in 2.1.1
